# This cloudbuild.yaml is used to test the php extension against multiple versions of php
steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build', '--build-arg', 'BASE_IMAGE=php:7.1', '.']
    waitFor: ['-']
    id: php71-nts
  - name: gcr.io/cloud-builders/docker
    args: ['build', '--build-arg', 'BASE_IMAGE=php:7.1-zts', '.']
    waitFor: ['-']
    id: php71-zts
  - name: gcr.io/cloud-builders/docker
    args: ['build', '--build-arg', 'BASE_IMAGE=php:7.0', '.']
    waitFor: ['-']
    id: php70-nts
  - name: gcr.io/cloud-builders/docker
    args: ['build', '--build-arg', 'BASE_IMAGE=php:7.0-zts', '.']
    waitFor: ['-']
    id: php70-zts
  - name: gcr.io/cloud-builders/docker
    args: ['build', '--build-arg', 'BASE_IMAGE=php:7.2', '.']
    waitFor: ['-']
    id: php72-nts
  - name: gcr.io/cloud-builders/docker
    args: ['build', '--build-arg', 'BASE_IMAGE=php:7.2-zts', '.']
    waitFor: ['-']
    id: php72-zts
  - name: gcr.io/cloud-builders/docker
    args: ['build', '--build-arg', 'BASE_IMAGE=gcr.io/php-stackdriver/php71-debug', '.']
    waitFor: ['-']
    id: php71-debug

  # integration test
  - name: gcr.io/cloud-builders/docker
    args: ['network', 'create', '-d', 'bridge', 'nw_jaeger']
    id: test-network
    waitFor: ['-']

  - name: gcr.io/cloud-builders/docker
    args:
    - 'run'
    - '-d'
    - '-e'
    - '-p6831:6831/udp'
    - '-p16686:16686'
    - '--name=jaeger-server'
    - '--network=nw_jaeger'
    - 'jaegertracing/all-in-one:latest'
    id: jaeger-server
    waitFor: ['test-network']

  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/test-runner', '-f', 'Dockerfile.integration',  '.']
    id: test-build
    waitFor: ['test-network']

  - name: gcr.io/cloud-builders/docker
    args: ['run', '--network=nw_jaeger', '-e', 'JAEGER_HOST=jaeger-server', 'gcr.io/$PROJECT_ID/test-runner', 'vendor/bin/phpunit', '--config=./phpunit-integration.xml.dist']
    id: test-run
    waitFor: ['test-build', 'jaeger-server']
